services:
  - type: web
    name: rotasyon-defteri
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
      - key: APP_USERNAME
        sync: false
      - key: APP_PASSWORD
        sync: false
